/*

The MIT License (MIT)

Copyright (c) 2014 Guillermo Rauch


Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
 https://mths.be/utf8js v2.1.2 by @mathias */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(p){var g=0;return function(){return g<p.length?{done:!1,value:p[g++]}:{done:!0}}};$jscomp.arrayIterator=function(p){return{next:$jscomp.arrayIteratorImpl(p)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(p,g,f){p!=Array.prototype&&p!=Object.prototype&&(p[g]=f.value)};$jscomp.getGlobal=function(p){p=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,p];for(var g=0;g<p.length;++g){var f=p[g];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(p,g){this.$jscomp$symbol$id_=p;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function p(f){if(this instanceof p)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+g++,f)}var g=0;return p}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var p=$jscomp.global.Symbol.iterator;p||(p=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[p]&&$jscomp.defineProperty(Array.prototype,p,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var p=$jscomp.global.Symbol.asyncIterator;p||(p=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(p){$jscomp.initSymbolIterator();p={next:p};p[$jscomp.global.Symbol.iterator]=function(){return this};return p};
$jscomp.iteratorFromArray=function(p,g){$jscomp.initSymbolIterator();p instanceof String&&(p+="");var f=0,c={next:function(){if(f<p.length){var d=f++;return{value:g(d,p[d]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(p,g,f,c){if(g){f=$jscomp.global;p=p.split(".");for(c=0;c<p.length-1;c++){var d=p[c];d in f||(f[d]={});f=f[d]}p=p[p.length-1];c=f[p];g=g(c);g!=c&&null!=g&&$jscomp.defineProperty(f,p,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.keys",function(p){return p?p:function(){return $jscomp.iteratorFromArray(this,function(g){return g})}},"es6","es3");
(function(p,g){"object"===typeof exports&&"object"===typeof module?module.exports=g():"function"===typeof define&&define.amd?define([],g):"object"===typeof exports?exports.io=g():p.io=g()})(this,function(){return function(p){function g(c){if(f[c])return f[c].exports;var d=f[c]={exports:{},id:c,loaded:!1};p[c].call(d.exports,d,d.exports,g);d.loaded=!0;return d.exports}var f={};g.m=p;g.c=f;g.p="";return g(0)}([function(p,g,f){function c(u,t){"object"===("undefined"===typeof u?"undefined":d(u))&&(t=
u,u=void 0);t=t||{};u=e(u);var h=u.source,a=u.id,b=u.path;b=v[a]&&b in v[a].nsps;t.forceNew||t["force new connection"]||!1===t.multiplex||b?(r("ignoring socket cache for %s",h),h=n(h,t)):(v[a]||(r("new io instance for %s",h),v[a]=n(h,t)),h=v[a]);u.query&&!t.query&&(t.query=u.query);return h.socket(u.path,t)}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(u){return typeof u}:function(u){return u&&"function"===typeof Symbol&&u.constructor===Symbol&&u!==Symbol.prototype?
"symbol":typeof u},e=f(1),l=f(7),n=f(12),r=f(3)("socket.io-client");p.exports=g=c;var v=g.managers={};g.protocol=l.protocol;g.connect=c;g.Manager=f(12);g.Socket=f(37)},function(p,g,f){(function(c){var d=f(2),e=f(3)("socket.io-client:url");p.exports=function(l,n){var r=l;n=n||c.location;null==l&&(l=n.protocol+"//"+n.host);"string"===typeof l&&("/"===l.charAt(0)&&(l="/"===l.charAt(1)?n.protocol+l:n.host+l),/^(https?|wss?):\/\//.test(l)||(e("protocol-less url %s",l),l="undefined"!==typeof n?n.protocol+
"//"+l:"https://"+l),e("parse %s",l),r=d(l));r.port||(/^(http|ws)$/.test(r.protocol)?r.port="80":/^(http|ws)s$/.test(r.protocol)&&(r.port="443"));r.path=r.path||"/";l=-1!==r.host.indexOf(":")?"["+r.host+"]":r.host;r.id=r.protocol+"://"+l+":"+r.port;r.href=r.protocol+"://"+l+(n&&n.port===r.port?"":":"+r.port);return r}}).call(g,function(){return this}())},function(p,g){var f=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,
c="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");p.exports=function(d){var e=d,l=d.indexOf("["),n=d.indexOf("]");-1!=l&&-1!=n&&(d=d.substring(0,l)+d.substring(l,n).replace(/:/g,";")+d.substring(n,d.length));d=f.exec(d||"");for(var r={},v=14;v--;)r[c[v]]=d[v]||"";-1!=l&&-1!=n&&(r.source=e,r.host=r.host.substring(1,r.host.length-1).replace(/;/g,":"),r.authority=r.authority.replace("[","").replace("]","").replace(/;/g,":"),r.ipv6uri=
!0);return r}},function(p,g,f){(function(c){function d(){try{var n=g.storage.debug}catch(r){}!n&&"undefined"!==typeof c&&"env"in c&&(n=c.env.DEBUG);return n}g=p.exports=f(5);g.log=function(){return"object"===typeof console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)};g.formatArgs=function(n){var r=this.useColors;n[0]=(r?"%c":"")+this.namespace+(r?" %c":" ")+n[0]+(r?"%c ":" ")+"+"+g.humanize(this.diff);if(r){r="color: "+this.color;n.splice(1,0,r,"color: inherit");var v=
0,u=0;n[0].replace(/%[a-zA-Z%]/g,function(t){"%%"!==t&&(v++,"%c"===t&&(u=v))});n.splice(u,0,r)}};g.save=function(n){try{null==n?g.storage.removeItem("debug"):g.storage.debug=n}catch(r){}};g.load=d;g.useColors=function(){return"undefined"!==typeof window&&window.process&&"renderer"===window.process.type?!0:"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/(edge|trident)\/(\d+)/)?!1:"undefined"!==typeof document&&document.documentElement&&document.documentElement.style&&
document.documentElement.style.WebkitAppearance||"undefined"!==typeof window&&window.console&&(window.console.firebug||window.console.exception&&window.console.table)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/firefox\/(\d+)/)&&31<=parseInt(RegExp.$1,10)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/applewebkit\/(\d+)/)};var e=g;if("undefined"!=typeof chrome&&"undefined"!=typeof chrome.storage)var l=
chrome.storage.local;else a:{try{l=window.localStorage;break a}catch(n){}l=void 0}e.storage=l;g.colors="#0000CC #0000FF #0033CC #0033FF #0066CC #0066FF #0099CC #0099FF #00CC00 #00CC33 #00CC66 #00CC99 #00CCCC #00CCFF #3300CC #3300FF #3333CC #3333FF #3366CC #3366FF #3399CC #3399FF #33CC00 #33CC33 #33CC66 #33CC99 #33CCCC #33CCFF #6600CC #6600FF #6633CC #6633FF #66CC00 #66CC33 #9900CC #9900FF #9933CC #9933FF #99CC00 #99CC33 #CC0000 #CC0033 #CC0066 #CC0099 #CC00CC #CC00FF #CC3300 #CC3333 #CC3366 #CC3399 #CC33CC #CC33FF #CC6600 #CC6633 #CC9900 #CC9933 #CCCC00 #CCCC33 #FF0000 #FF0033 #FF0066 #FF0099 #FF00CC #FF00FF #FF3300 #FF3333 #FF3366 #FF3399 #FF33CC #FF33FF #FF6600 #FF6633 #FF9900 #FF9933 #FFCC00 #FFCC33".split(" ");
g.formatters.j=function(n){try{return JSON.stringify(n)}catch(r){return"[UnexpectedJSONParseError]: "+r.message}};g.enable(d())}).call(g,f(4))},function(p,g){function f(){throw Error("setTimeout has not been defined");}function c(){throw Error("clearTimeout has not been defined");}function d(m){if(u===setTimeout)return setTimeout(m,0);if((u===f||!u)&&setTimeout)return u=setTimeout,setTimeout(m,0);try{return u(m,0)}catch(w){try{return u.call(null,m,0)}catch(B){return u.call(this,m,0)}}}function e(m){if(t===
clearTimeout)return clearTimeout(m);if((t===c||!t)&&clearTimeout)return t=clearTimeout,clearTimeout(m);try{return t(m)}catch(w){try{return t.call(null,m)}catch(B){return t.call(this,m)}}}function l(){a&&b&&(a=!1,b.length?h=b.concat(h):k=-1,h.length&&n())}function n(){if(!a){var m=d(l);a=!0;for(var w=h.length;w;){b=h;for(h=[];++k<w;)b&&b[k].run();k=-1;w=h.length}b=null;a=!1;e(m)}}function r(m,w){this.fun=m;this.array=w}function v(){}p=p.exports={};try{var u="function"===typeof setTimeout?setTimeout:
f}catch(m){u=f}try{var t="function"===typeof clearTimeout?clearTimeout:c}catch(m){t=c}var h=[],a=!1,b,k=-1;p.nextTick=function(m){var w=Array(arguments.length-1);if(1<arguments.length)for(var B=1;B<arguments.length;B++)w[B-1]=arguments[B];h.push(new r(m,w));1!==h.length||a||d(n)};r.prototype.run=function(){this.fun.apply(null,this.array)};p.title="browser";p.browser=!0;p.env={};p.argv=[];p.version="";p.versions={};p.on=v;p.addListener=v;p.once=v;p.off=v;p.removeListener=v;p.removeAllListeners=v;p.emit=
v;p.prependListener=v;p.prependOnceListener=v;p.listeners=function(m){return[]};p.binding=function(m){throw Error("process.binding is not supported");};p.cwd=function(){return"/"};p.chdir=function(m){throw Error("process.chdir is not supported");};p.umask=function(){return 0}},function(p,g,f){function c(l){var n=0,r;for(r in l)n=(n<<5)-n+l.charCodeAt(r),n|=0;return g.colors[Math.abs(n)%g.colors.length]}function d(l){function n(){if(n.enabled){var v=+new Date;n.diff=v-(r||v);n.prev=r;r=n.curr=v;var u=
Array(arguments.length);for(v=0;v<u.length;v++)u[v]=arguments[v];u[0]=g.coerce(u[0]);"string"!==typeof u[0]&&u.unshift("%O");var t=0;u[0]=u[0].replace(/%([a-zA-Z%])/g,function(h,a){if("%%"===h)return h;t++;a=g.formatters[a];"function"===typeof a&&(h=a.call(n,u[t]),u.splice(t,1),t--);return h});g.formatArgs.call(n,u);(n.log||g.log||console.log.bind(console)).apply(n,u)}}var r;n.namespace=l;n.enabled=g.enabled(l);n.useColors=g.useColors();n.color=c(l);n.destroy=e;"function"===typeof g.init&&g.init(n);
g.instances.push(n);return n}function e(){var l=g.instances.indexOf(this);return-1!==l?(g.instances.splice(l,1),!0):!1}g=p.exports=d.debug=d["default"]=d;g.coerce=function(l){return l instanceof Error?l.stack||l.message:l};g.disable=function(){g.enable("")};g.enable=function(l){g.save(l);g.names=[];g.skips=[];var n,r=("string"===typeof l?l:"").split(/[\s,]+/),v=r.length;for(n=0;n<v;n++)r[n]&&(l=r[n].replace(/\*/g,".*?"),"-"===l[0]?g.skips.push(new RegExp("^"+l.substr(1)+"$")):g.names.push(new RegExp("^"+
l+"$")));for(n=0;n<g.instances.length;n++)l=g.instances[n],l.enabled=g.enabled(l.namespace)};g.enabled=function(l){if("*"===l[l.length-1])return!0;var n;var r=0;for(n=g.skips.length;r<n;r++)if(g.skips[r].test(l))return!1;r=0;for(n=g.names.length;r<n;r++)if(g.names[r].test(l))return!0;return!1};g.humanize=f(6);g.instances=[];g.names=[];g.skips=[];g.formatters={}},function(p,g){function f(e){e=String(e);if(!(100<e.length)&&(e=/^((?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|years?|yrs?|y)?$/i.exec(e))){var l=
parseFloat(e[1]);switch((e[2]||"ms").toLowerCase()){case "years":case "year":case "yrs":case "yr":case "y":return l*d;case "days":case "day":case "d":return 864E5*l;case "hours":case "hour":case "hrs":case "hr":case "h":return 36E5*l;case "minutes":case "minute":case "mins":case "min":case "m":return 6E4*l;case "seconds":case "second":case "secs":case "sec":case "s":return 1E3*l;case "milliseconds":case "millisecond":case "msecs":case "msec":case "ms":return l}}}function c(e,l,n){if(!(e<l))return e<
1.5*l?Math.floor(e/l)+" "+n:Math.ceil(e/l)+" "+n+"s"}var d=315576E5;p.exports=function(e,l){l=l||{};var n=typeof e;if("string"===n&&0<e.length)return f(e);if("number"===n&&!1===isNaN(e))return l.long?c(e,864E5,"day")||c(e,36E5,"hour")||c(e,6E4,"minute")||c(e,1E3,"second")||e+" ms":864E5<=e?Math.round(e/864E5)+"d":36E5<=e?Math.round(e/36E5)+"h":6E4<=e?Math.round(e/6E4)+"m":1E3<=e?Math.round(e/1E3)+"s":e+"ms";throw Error("val is not a non-empty string or a valid number. val="+JSON.stringify(e));}},
function(p,g,f){function c(){}function d(a){var b=""+a.type;if(g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type)b+=a.attachments+"-";a.nsp&&"/"!==a.nsp&&(b+=a.nsp+",");null!=a.id&&(b+=a.id);if(null!=a.data){try{var k=JSON.stringify(a.data)}catch(m){k=!1}if(!1!==k)b+=k;else return h}r("encoded %j as %s",a,b);return b}function e(a,b){v.removeBlobs(a,function(k){var m=v.deconstructPacket(k);k=d(m.packet);m=m.buffers;m.unshift(k);b(m)})}function l(){this.reconstructor=null}function n(a){this.reconPack=
a;this.buffers=[]}var r=f(3)("socket.io-parser");p=f(8);var v=f(9),u=f(10),t=f(11);g.protocol=4;g.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");g.CONNECT=0;g.DISCONNECT=1;g.EVENT=2;g.ACK=3;g.ERROR=4;g.BINARY_EVENT=5;g.BINARY_ACK=6;g.Encoder=c;g.Decoder=l;var h=g.ERROR+'"encode error"';c.prototype.encode=function(a,b){r("encoding packet %j",a);g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type?e(a,b):(a=d(a),b([a]))};p(l.prototype);l.prototype.add=function(a){if("string"===
typeof a){a:{var b=0,k={type:Number(a.charAt(0))};if(null==g.types[k.type])a={type:g.ERROR,data:"parser error: unknown packet type "+k.type};else{if(g.BINARY_EVENT===k.type||g.BINARY_ACK===k.type){for(var m="";"-"!==a.charAt(++b)&&(m+=a.charAt(b),b!=a.length););if(m!=Number(m)||"-"!==a.charAt(b))throw Error("Illegal attachments");k.attachments=Number(m)}if("/"===a.charAt(b+1))for(k.nsp="";++b;){m=a.charAt(b);if(","===m)break;k.nsp+=m;if(b===a.length)break}else k.nsp="/";m=a.charAt(b+1);if(""!==m&&
Number(m)==m){for(k.id="";++b;){m=a.charAt(b);if(null==m||Number(m)!=m){--b;break}k.id+=a.charAt(b);if(b===a.length)break}k.id=Number(k.id)}if(a.charAt(++b)){b=a.substr(b);try{var w=JSON.parse(b)}catch(B){w=!1}if(!1===w||k.type!==g.ERROR&&!u(w)){a={type:g.ERROR,data:"parser error: invalid payload"};break a}else k.data=w}r("decoded %s as %j",a,k);a=k}}g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type?(this.reconstructor=new n(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",
a)}else if(t(a)||a.base64)if(this.reconstructor){if(a=this.reconstructor.takeBinaryData(a))this.reconstructor=null,this.emit("decoded",a)}else throw Error("got binary data when not reconstructing a packet");else throw Error("Unknown type: "+a);};l.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};n.prototype.takeBinaryData=function(a){this.buffers.push(a);return this.buffers.length===this.reconPack.attachments?(a=v.reconstructPacket(this.reconPack,this.buffers),
this.finishedReconstruction(),a):null};n.prototype.finishedReconstruction=function(){this.reconPack=null;this.buffers=[]}},function(p,g,f){function c(d){if(d){for(var e in c.prototype)d[e]=c.prototype[e];return d}}p.exports=c;c.prototype.on=c.prototype.addEventListener=function(d,e){this._callbacks=this._callbacks||{};(this._callbacks["$"+d]=this._callbacks["$"+d]||[]).push(e);return this};c.prototype.once=function(d,e){function l(){this.off(d,l);e.apply(this,arguments)}l.fn=e;this.on(d,l);return this};
c.prototype.off=c.prototype.removeListener=c.prototype.removeAllListeners=c.prototype.removeEventListener=function(d,e){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks={},this;var l=this._callbacks["$"+d];if(!l)return this;if(1==arguments.length)return delete this._callbacks["$"+d],this;for(var n,r=0;r<l.length;r++)if(n=l[r],n===e||n.fn===e){l.splice(r,1);break}return this};c.prototype.emit=function(d){this._callbacks=this._callbacks||{};var e=[].slice.call(arguments,
1),l=this._callbacks["$"+d];if(l){l=l.slice(0);for(var n=0,r=l.length;n<r;++n)l[n].apply(this,e)}return this};c.prototype.listeners=function(d){this._callbacks=this._callbacks||{};return this._callbacks["$"+d]||[]};c.prototype.hasListeners=function(d){return!!this.listeners(d).length}},function(p,g,f){(function(c){function d(t,h){if(!t)return t;if(n(t)){var a={_placeholder:!0,num:h.length};h.push(t);return a}if(l(t)){a=Array(t.length);for(var b=0;b<t.length;b++)a[b]=d(t[b],h);return a}if("object"===
typeof t&&!(t instanceof Date)){a={};for(b in t)a[b]=d(t[b],h);return a}return t}function e(t,h){if(!t)return t;if(t&&t._placeholder)return h[t.num];if(l(t))for(var a=0;a<t.length;a++)t[a]=e(t[a],h);else if("object"===typeof t)for(a in t)t[a]=e(t[a],h);return t}var l=f(10),n=f(11),r=Object.prototype.toString,v="function"===typeof c.Blob||"[object BlobConstructor]"===r.call(c.Blob),u="function"===typeof c.File||"[object FileConstructor]"===r.call(c.File);g.deconstructPacket=function(t){var h=[];t.data=
d(t.data,h);t.attachments=h.length;return{packet:t,buffers:h}};g.reconstructPacket=function(t,h){t.data=e(t.data,h);t.attachments=void 0;return t};g.removeBlobs=function(t,h){function a(m,w,B){if(!m)return m;if(v&&m instanceof Blob||u&&m instanceof File){b++;var q=new FileReader;q.onload=function(){B?B[w]=this.result:k=this.result;--b||h(k)};q.readAsArrayBuffer(m)}else if(l(m))for(q=0;q<m.length;q++)a(m[q],q,m);else if("object"===typeof m&&!n(m))for(q in m)a(m[q],q,m)}var b=0,k=t;a(k);b||h(k)}}).call(g,
function(){return this}())},function(p,g){var f={}.toString;p.exports=Array.isArray||function(c){return"[object Array]"==f.call(c)}},function(p,g){(function(f){p.exports=function(l){return c&&f.Buffer.isBuffer(l)||d&&(l instanceof f.ArrayBuffer||e(l))};var c="function"===typeof f.Buffer&&"function"===typeof f.Buffer.isBuffer,d="function"===typeof f.ArrayBuffer,e=function(){return d&&"function"===typeof f.ArrayBuffer.isView?f.ArrayBuffer.isView:function(l){return l.buffer instanceof f.ArrayBuffer}}()}).call(g,
function(){return this}())},function(p,g,f){function c(b,k){if(!(this instanceof c))return new c(b,k);b&&"object"===("undefined"===typeof b?"undefined":d(b))&&(k=b,b=void 0);k=k||{};k.path=k.path||"/socket.io";this.nsps={};this.subs=[];this.opts=k;this.reconnection(!1!==k.reconnection);this.reconnectionAttempts(k.reconnectionAttempts||Infinity);this.reconnectionDelay(k.reconnectionDelay||1E3);this.reconnectionDelayMax(k.reconnectionDelayMax||5E3);this.randomizationFactor(k.randomizationFactor||.5);
this.backoff=new h({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),jitter:this.randomizationFactor()});this.timeout(null==k.timeout?2E4:k.timeout);this.readyState="closed";this.uri=b;this.connecting=[];this.lastPing=null;this.encoding=!1;this.packetBuffer=[];var m=k.parser||n;this.encoder=new m.Encoder;this.decoder=new m.Decoder;(this.autoConnect=!1!==k.autoConnect)&&this.open()}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&
"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b},e=f(13),l=f(37);g=f(8);var n=f(7),r=f(39),v=f(40),u=f(3)("socket.io-client:manager"),t=f(36),h=f(41),a=Object.prototype.hasOwnProperty;p.exports=c;c.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var b in this.nsps)a.call(this.nsps,b)&&this.nsps[b].emit.apply(this.nsps[b],arguments)};c.prototype.updateSocketIds=function(){for(var b in this.nsps)a.call(this.nsps,b)&&(this.nsps[b].id=this.generateId(b))};
c.prototype.generateId=function(b){return("/"===b?"":b+"#")+this.engine.id};g(c.prototype);c.prototype.reconnection=function(b){if(!arguments.length)return this._reconnection;this._reconnection=!!b;return this};c.prototype.reconnectionAttempts=function(b){if(!arguments.length)return this._reconnectionAttempts;this._reconnectionAttempts=b;return this};c.prototype.reconnectionDelay=function(b){if(!arguments.length)return this._reconnectionDelay;this._reconnectionDelay=b;this.backoff&&this.backoff.setMin(b);
return this};c.prototype.randomizationFactor=function(b){if(!arguments.length)return this._randomizationFactor;this._randomizationFactor=b;this.backoff&&this.backoff.setJitter(b);return this};c.prototype.reconnectionDelayMax=function(b){if(!arguments.length)return this._reconnectionDelayMax;this._reconnectionDelayMax=b;this.backoff&&this.backoff.setMax(b);return this};c.prototype.timeout=function(b){if(!arguments.length)return this._timeout;this._timeout=b;return this};c.prototype.maybeReconnectOnOpen=
function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};c.prototype.open=c.prototype.connect=function(b,k){u("readyState %s",this.readyState);if(~this.readyState.indexOf("open"))return this;u("opening %s",this.uri);var m=this.engine=e(this.uri,this.opts),w=this;this.readyState="opening";this.skipReconnect=!1;var B=r(m,"open",function(){w.onopen();b&&b()});k=r(m,"error",function(y){u("connect_error");w.cleanup();w.readyState="closed";w.emitAll("connect_error",
y);if(b){var z=Error("Connection error");z.data=y;b(z)}else w.maybeReconnectOnOpen()});if(!1!==this._timeout){var q=this._timeout;u("connect attempt will timeout after %d",q);var x=setTimeout(function(){u("connect attempt timed out after %d",q);B.destroy();m.close();m.emit("error","timeout");w.emitAll("connect_timeout",q)},q);this.subs.push({destroy:function(){clearTimeout(x)}})}this.subs.push(B);this.subs.push(k);return this};c.prototype.onopen=function(){u("open");this.cleanup();this.readyState=
"open";this.emit("open");var b=this.engine;this.subs.push(r(b,"data",v(this,"ondata")));this.subs.push(r(b,"ping",v(this,"onping")));this.subs.push(r(b,"pong",v(this,"onpong")));this.subs.push(r(b,"error",v(this,"onerror")));this.subs.push(r(b,"close",v(this,"onclose")));this.subs.push(r(this.decoder,"decoded",v(this,"ondecoded")))};c.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};c.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};c.prototype.ondata=
function(b){this.decoder.add(b)};c.prototype.ondecoded=function(b){this.emit("packet",b)};c.prototype.onerror=function(b){u("error",b);this.emitAll("error",b)};c.prototype.socket=function(b,k){function m(){~t(B.connecting,w)||B.connecting.push(w)}var w=this.nsps[b];if(!w){w=new l(this,b,k);this.nsps[b]=w;var B=this;w.on("connecting",m);w.on("connect",function(){w.id=B.generateId(b)});this.autoConnect&&m()}return w};c.prototype.destroy=function(b){b=t(this.connecting,b);~b&&this.connecting.splice(b,
1);this.connecting.length||this.close()};c.prototype.packet=function(b){u("writing packet %j",b);var k=this;b.query&&0===b.type&&(b.nsp+="?"+b.query);k.encoding?k.packetBuffer.push(b):(k.encoding=!0,this.encoder.encode(b,function(m){for(var w=0;w<m.length;w++)k.engine.write(m[w],b.options);k.encoding=!1;k.processPacketQueue()}))};c.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var b=this.packetBuffer.shift();this.packet(b)}};c.prototype.cleanup=function(){u("cleanup");
for(var b=this.subs.length,k=0;k<b;k++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;this.decoder.destroy()};c.prototype.close=c.prototype.disconnect=function(){u("disconnect");this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};c.prototype.onclose=function(b){u("onclose");this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",
b);this._reconnection&&!this.skipReconnect&&this.reconnect()};c.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;var b=this;if(this.backoff.attempts>=this._reconnectionAttempts)u("reconnect failed"),this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var k=this.backoff.duration();u("will wait %dms before reconnect attempt",k);this.reconnecting=!0;var m=setTimeout(function(){b.skipReconnect||(u("attempting reconnect"),b.emitAll("reconnect_attempt",
b.backoff.attempts),b.emitAll("reconnecting",b.backoff.attempts),b.skipReconnect||b.open(function(w){w?(u("reconnect attempt error"),b.reconnecting=!1,b.reconnect(),b.emitAll("reconnect_error",w.data)):(u("reconnect success"),b.onreconnect())}))},k);this.subs.push({destroy:function(){clearTimeout(m)}})}};c.prototype.onreconnect=function(){var b=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",b)}},function(p,g,f){p.exports=f(14);p.exports.parser=
f(21)},function(p,g,f){(function(c){function d(h,a){if(!(this instanceof d))return new d(h,a);a=a||{};h&&"object"===typeof h&&(a=h,h=null);h?(h=u(h),a.hostname=h.host,a.secure="https"===h.protocol||"wss"===h.protocol,a.port=h.port,h.query&&(a.query=h.query)):a.host&&(a.hostname=u(a.host).host);this.secure=null!=a.secure?a.secure:c.location&&"https:"===location.protocol;a.hostname&&!a.port&&(a.port=this.secure?"443":"80");this.agent=a.agent||!1;this.hostname=a.hostname||(c.location?location.hostname:
"localhost");this.port=a.port||(c.location&&location.port?location.port:this.secure?443:80);this.query=a.query||{};"string"===typeof this.query&&(this.query=t.decode(this.query));this.upgrade=!1!==a.upgrade;this.path=(a.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!a.forceJSONP;this.jsonp=!1!==a.jsonp;this.forceBase64=!!a.forceBase64;this.enablesXDR=!!a.enablesXDR;this.timestampParam=a.timestampParam||"t";this.timestampRequests=a.timestampRequests;this.transports=a.transports||["polling",
"websocket"];this.transportOptions=a.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=a.policyPort||843;this.rememberUpgrade=a.rememberUpgrade||!1;this.binaryType=null;this.onlyBinaryUpgrades=a.onlyBinaryUpgrades;this.perMessageDeflate=!1!==a.perMessageDeflate?a.perMessageDeflate||{}:!1;!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=
a.pfx||null;this.key=a.key||null;this.passphrase=a.passphrase||null;this.cert=a.cert||null;this.ca=a.ca||null;this.ciphers=a.ciphers||null;this.rejectUnauthorized=void 0===a.rejectUnauthorized?!0:a.rejectUnauthorized;this.forceNode=!!a.forceNode;h="object"===typeof c&&c;h.global===h&&(a.extraHeaders&&0<Object.keys(a.extraHeaders).length&&(this.extraHeaders=a.extraHeaders),a.localAddress&&(this.localAddress=a.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=
this.upgrades=this.id=null;this.open()}var e=f(15),l=f(8),n=f(3)("engine.io-client:socket"),r=f(36),v=f(21),u=f(2),t=f(30);p.exports=d;d.priorWebsocketSuccess=!1;l(d.prototype);d.protocol=v.protocol;d.Socket=d;d.Transport=f(20);d.transports=f(15);d.parser=f(21);d.prototype.createTransport=function(h){n('creating transport "%s"',h);var a=this.query,b={},k;for(k in a)a.hasOwnProperty(k)&&(b[k]=a[k]);b.EIO=v.protocol;b.transport=h;a=this.transportOptions[h]||{};this.id&&(b.sid=this.id);return new e[h]({query:b,
socket:this,agent:a.agent||this.agent,hostname:a.hostname||this.hostname,port:a.port||this.port,secure:a.secure||this.secure,path:a.path||this.path,forceJSONP:a.forceJSONP||this.forceJSONP,jsonp:a.jsonp||this.jsonp,forceBase64:a.forceBase64||this.forceBase64,enablesXDR:a.enablesXDR||this.enablesXDR,timestampRequests:a.timestampRequests||this.timestampRequests,timestampParam:a.timestampParam||this.timestampParam,policyPort:a.policyPort||this.policyPort,pfx:a.pfx||this.pfx,key:a.key||this.key,passphrase:a.passphrase||
this.passphrase,cert:a.cert||this.cert,ca:a.ca||this.ca,ciphers:a.ciphers||this.ciphers,rejectUnauthorized:a.rejectUnauthorized||this.rejectUnauthorized,perMessageDeflate:a.perMessageDeflate||this.perMessageDeflate,extraHeaders:a.extraHeaders||this.extraHeaders,forceNode:a.forceNode||this.forceNode,localAddress:a.localAddress||this.localAddress,requestTimeout:a.requestTimeout||this.requestTimeout,protocols:a.protocols||void 0})};d.prototype.open=function(){if(this.rememberUpgrade&&d.priorWebsocketSuccess&&
-1!==this.transports.indexOf("websocket"))var h="websocket";else{if(0===this.transports.length){var a=this;setTimeout(function(){a.emit("error","No transports available")},0);return}h=this.transports[0]}this.readyState="opening";try{h=this.createTransport(h)}catch(b){this.transports.shift();this.open();return}h.open();this.setTransport(h)};d.prototype.setTransport=function(h){n("setting transport %s",h.name);var a=this;this.transport&&(n("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());
this.transport=h;h.on("drain",function(){a.onDrain()}).on("packet",function(b){a.onPacket(b)}).on("error",function(b){a.onError(b)}).on("close",function(){a.onClose("transport close")})};d.prototype.probe=function(h){function a(){if(z.onlyBinaryUpgrades){var A=!this.supportsBinary&&z.transport.supportsBinary;y=y||A}y||(n('probe transport "%s" opened',h),x.send([{type:"ping",data:"probe"}]),x.once("packet",function(C){y||("pong"===C.type&&"probe"===C.data?(n('probe transport "%s" pong',h),z.upgrading=
!0,z.emit("upgrading",x),x&&(d.priorWebsocketSuccess="websocket"===x.name,n('pausing current transport "%s"',z.transport.name),z.transport.pause(function(){y||"closed"===z.readyState||(n("changing transport and sending upgrade packet"),q(),z.setTransport(x),x.send([{type:"upgrade"}]),z.emit("upgrade",x),x=null,z.upgrading=!1,z.flush())}))):(n('probe transport "%s" failed',h),C=Error("probe error"),C.transport=x.name,z.emit("upgradeError",C)))}))}function b(){y||(y=!0,q(),x.close(),x=null)}function k(A){var C=
Error("probe error: "+A);C.transport=x.name;b();n('probe transport "%s" failed because of error: %s',h,A);z.emit("upgradeError",C)}function m(){k("transport closed")}function w(){k("socket closed")}function B(A){x&&A.name!==x.name&&(n('"%s" works - aborting "%s"',A.name,x.name),b())}function q(){x.removeListener("open",a);x.removeListener("error",k);x.removeListener("close",m);z.removeListener("close",w);z.removeListener("upgrading",B)}n('probing transport "%s"',h);var x=this.createTransport(h,{probe:1}),
y=!1,z=this;d.priorWebsocketSuccess=!1;x.once("open",a);x.once("error",k);x.once("close",m);this.once("close",w);this.once("upgrading",B);x.open()};d.prototype.onOpen=function(){n("socket open");this.readyState="open";d.priorWebsocketSuccess="websocket"===this.transport.name;this.emit("open");this.flush();if("open"===this.readyState&&this.upgrade&&this.transport.pause){n("starting upgrade probes");for(var h=0,a=this.upgrades.length;h<a;h++)this.probe(this.upgrades[h])}};d.prototype.onPacket=function(h){if("opening"===
this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(n('socket receive: type "%s", data "%s"',h.type,h.data),this.emit("packet",h),this.emit("heartbeat"),h.type){case "open":this.onHandshake(JSON.parse(h.data));break;case "pong":this.setPing();this.emit("pong");break;case "error":var a=Error("server error");a.code=h.data;this.onError(a);break;case "message":this.emit("data",h.data),this.emit("message",h.data)}else n('packet received with socket readyState "%s"',this.readyState)};
d.prototype.onHandshake=function(h){this.emit("handshake",h);this.id=h.sid;this.transport.query.sid=h.sid;this.upgrades=this.filterUpgrades(h.upgrades);this.pingInterval=h.pingInterval;this.pingTimeout=h.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};d.prototype.onHeartbeat=function(h){clearTimeout(this.pingTimeoutTimer);var a=this;a.pingTimeoutTimer=setTimeout(function(){if("closed"!==
a.readyState)a.onClose("ping timeout")},h||a.pingInterval+a.pingTimeout)};d.prototype.setPing=function(){var h=this;clearTimeout(h.pingIntervalTimer);h.pingIntervalTimer=setTimeout(function(){n("writing ping packet - expecting pong within %sms",h.pingTimeout);h.ping();h.onHeartbeat(h.pingTimeout)},h.pingInterval)};d.prototype.ping=function(){var h=this;this.sendPacket("ping",function(){h.emit("ping")})};d.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=
0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};d.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&(n("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};d.prototype.write=d.prototype.send=function(h,a,b){this.sendPacket("message",h,a,b);return this};d.prototype.sendPacket=function(h,a,b,k){"function"===typeof a&&
(k=a,a=void 0);"function"===typeof b&&(k=b,b=null);if("closing"!==this.readyState&&"closed"!==this.readyState){b=b||{};b.compress=!1!==b.compress;h={type:h,data:a,options:b};this.emit("packetCreate",h);this.writeBuffer.push(h);if(k)this.once("flush",k);this.flush()}};d.prototype.close=function(){function h(){k.onClose("forced close");n("socket closing - telling transport to close");k.transport.close()}function a(){k.removeListener("upgrade",a);k.removeListener("upgradeError",a);h()}function b(){k.once("upgrade",
a);k.once("upgradeError",a)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var k=this;if(this.writeBuffer.length)this.once("drain",function(){this.upgrading?b():h()});else this.upgrading?b():h()}return this};d.prototype.onError=function(h){n("socket error %j",h);d.priorWebsocketSuccess=!1;this.emit("error",h);this.onClose("transport error",h)};d.prototype.onClose=function(h,a){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)n('socket close with reason: "%s"',
h),clearTimeout(this.pingIntervalTimer),clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),this.readyState="closed",this.id=null,this.emit("close",h,a),this.writeBuffer=[],this.prevBufferLen=0};d.prototype.filterUpgrades=function(h){for(var a=[],b=0,k=h.length;b<k;b++)~r(this.transports,h[b])&&a.push(h[b]);return a}}).call(g,function(){return this}())},function(p,g,f){(function(c){var d=f(16),e=f(18),l=f(33),n=
f(34);g.polling=function(r){var v=!1,u=!1,t=!1!==r.jsonp;c.location&&(u="https:"===location.protocol,(v=location.port)||(v=u?443:80),v=r.hostname!==location.hostname||v!==r.port,u=r.secure!==u);r.xdomain=v;r.xscheme=u;if("open"in new d(r)&&!r.forceJSONP)return new e(r);if(!t)throw Error("JSONP disabled");return new l(r)};g.websocket=n}).call(g,function(){return this}())},function(p,g,f){(function(c){var d=f(17);p.exports=function(e){var l=e.xdomain,n=e.xscheme;e=e.enablesXDR;try{if("undefined"!==
typeof XMLHttpRequest&&(!l||d))return new XMLHttpRequest}catch(r){}try{if("undefined"!==typeof XDomainRequest&&!n&&e)return new XDomainRequest}catch(r){}if(!l)try{return new (c[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(r){}}}).call(g,function(){return this}())},function(p,g){try{p.exports="undefined"!==typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(f){p.exports=!1}},function(p,g,f){(function(c){function d(){}function e(a){v.call(this,a);this.requestTimeout=
a.requestTimeout;this.extraHeaders=a.extraHeaders;if(c.location){var b="https:"===location.protocol,k=location.port;k||(k=b?443:80);this.xd=a.hostname!==c.location.hostname||k!==a.port;this.xs=a.secure!==b}}function l(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;
this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function n(){for(var a in l.requests)l.requests.hasOwnProperty(a)&&l.requests[a].abort()}var r=f(16),v=f(19),u=f(8),t=f(31),h=f(3)("engine.io-client:polling-xhr");p.exports=e;p.exports.Request=l;t(e,v);e.prototype.supportsBinary=!0;e.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=this.xd;
a.xs=this.xs;a.agent=this.agent||!1;a.supportsBinary=this.supportsBinary;a.enablesXDR=this.enablesXDR;a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=this.rejectUnauthorized;a.requestTimeout=this.requestTimeout;a.extraHeaders=this.extraHeaders;return new l(a)};e.prototype.doWrite=function(a,b){a=this.request({method:"POST",data:a,isBinary:"string"!==typeof a&&void 0!==a});var k=this;a.on("success",b);a.on("error",
function(m){k.onError("xhr post error",m)});this.sendXhr=a};e.prototype.doPoll=function(){h("xhr poll");var a=this.request(),b=this;a.on("data",function(k){b.onData(k)});a.on("error",function(k){b.onError("xhr poll error",k)});this.pollXhr=a};u(l.prototype);l.prototype.create=function(){var a={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=
this.rejectUnauthorized;var b=this.xhr=new r(a),k=this;try{h("xhr open %s: %s",this.method,this.uri);b.open(this.method,this.uri,this.async);try{if(this.extraHeaders){b.setDisableHeaderCheck&&b.setDisableHeaderCheck(!0);for(var m in this.extraHeaders)this.extraHeaders.hasOwnProperty(m)&&b.setRequestHeader(m,this.extraHeaders[m])}}catch(w){}if("POST"===this.method)try{this.isBinary?b.setRequestHeader("Content-type","application/octet-stream"):b.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(w){}try{b.setRequestHeader("Accept",
"*/*")}catch(w){}"withCredentials"in b&&(b.withCredentials=!0);this.requestTimeout&&(b.timeout=this.requestTimeout);this.hasXDR()?(b.onload=function(){k.onLoad()},b.onerror=function(){k.onError(b.responseText)}):b.onreadystatechange=function(){if(2===b.readyState)try{var w=b.getResponseHeader("Content-Type");k.supportsBinary&&"application/octet-stream"===w&&(b.responseType="arraybuffer")}catch(B){}if(4===b.readyState)if(200===b.status||1223===b.status)k.onLoad();else setTimeout(function(){k.onError(b.status)},
0)};h("xhr data %s",this.data);b.send(this.data)}catch(w){setTimeout(function(){k.onError(w)},0);return}c.document&&(this.index=l.requestsCount++,l.requests[this.index]=this)};l.prototype.onSuccess=function(){this.emit("success");this.cleanup()};l.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};l.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};l.prototype.cleanup=function(a){if("undefined"!==typeof this.xhr&&null!==this.xhr){this.hasXDR()?this.xhr.onload=this.xhr.onerror=
d:this.xhr.onreadystatechange=d;if(a)try{this.xhr.abort()}catch(b){}c.document&&delete l.requests[this.index];this.xhr=null}};l.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(k){}var b="application/octet-stream"===a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(k){this.onError(k)}if(null!=b)this.onData(b)};l.prototype.hasXDR=function(){return"undefined"!==typeof c.XDomainRequest&&!this.xs&&this.enablesXDR};l.prototype.abort=function(){this.cleanup()};
l.requestsCount=0;l.requests={};c.document&&(c.attachEvent?c.attachEvent("onunload",n):c.addEventListener&&c.addEventListener("beforeunload",n,!1))}).call(g,function(){return this}())},function(p,g,f){function c(u){var t=u&&u.forceBase64;if(!v||t)this.supportsBinary=!1;d.call(this,u)}var d=f(20),e=f(30),l=f(21);g=f(31);var n=f(32),r=f(3)("engine.io-client:polling");p.exports=c;var v=null!=(new (f(16))({xdomain:!1})).responseType;g(c,d);c.prototype.name="polling";c.prototype.doOpen=function(){this.poll()};
c.prototype.pause=function(u){function t(){r("paused");h.readyState="paused";u()}var h=this;this.readyState="pausing";if(this.polling||!this.writable){var a=0;this.polling&&(r("we are currently polling - waiting to pause"),a++,this.once("pollComplete",function(){r("pre-pause polling complete");--a||t()}));this.writable||(r("we are currently writing - waiting to pause"),a++,this.once("drain",function(){r("pre-pause writing complete");--a||t()}))}else t()};c.prototype.poll=function(){r("polling");this.polling=
!0;this.doPoll();this.emit("poll")};c.prototype.onData=function(u){var t=this;r("polling got data %s",u);l.decodePayload(u,this.socket.binaryType,function(h,a,b){if("opening"===t.readyState)t.onOpen();if("close"===h.type)return t.onClose(),!1;t.onPacket(h)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState?this.poll():r('ignoring poll - transport state "%s"',this.readyState))};c.prototype.doClose=function(){function u(){r("writing close packet");t.write([{type:"close"}])}
var t=this;"open"===this.readyState?(r("transport open - closing"),u()):(r("transport not open - deferring close"),this.once("open",u))};c.prototype.write=function(u){var t=this;this.writable=!1;var h=function(){t.writable=!0;t.emit("drain")};l.encodePayload(u,this.supportsBinary,function(a){t.doWrite(a,h)})};c.prototype.uri=function(){var u=this.query||{},t=this.secure?"https":"http",h="";!1!==this.timestampRequests&&(u[this.timestampParam]=n());this.supportsBinary||u.sid||(u.b64=1);u=e.encode(u);
this.port&&("https"===t&&443!==Number(this.port)||"http"===t&&80!==Number(this.port))&&(h=":"+this.port);u.length&&(u="?"+u);var a=-1!==this.hostname.indexOf(":");return t+"://"+(a?"["+this.hostname+"]":this.hostname)+h+this.path+u}},function(p,g,f){function c(e){this.path=e.path;this.hostname=e.hostname;this.port=e.port;this.secure=e.secure;this.query=e.query;this.timestampParam=e.timestampParam;this.timestampRequests=e.timestampRequests;this.readyState="";this.agent=e.agent||!1;this.socket=e.socket;
this.enablesXDR=e.enablesXDR;this.pfx=e.pfx;this.key=e.key;this.passphrase=e.passphrase;this.cert=e.cert;this.ca=e.ca;this.ciphers=e.ciphers;this.rejectUnauthorized=e.rejectUnauthorized;this.forceNode=e.forceNode;this.extraHeaders=e.extraHeaders;this.localAddress=e.localAddress}var d=f(21);g=f(8);p.exports=c;g(c.prototype);c.prototype.onError=function(e,l){e=Error(e);e.type="TransportError";e.description=l;this.emit("error",e);return this};c.prototype.open=function(){if("closed"===this.readyState||
""===this.readyState)this.readyState="opening",this.doOpen();return this};c.prototype.close=function(){if("opening"===this.readyState||"open"===this.readyState)this.doClose(),this.onClose();return this};c.prototype.send=function(e){if("open"===this.readyState)this.write(e);else throw Error("Transport not open");};c.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};c.prototype.onData=function(e){e=d.decodePacket(e,this.socket.binaryType);this.onPacket(e)};c.prototype.onPacket=
function(e){this.emit("packet",e)};c.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},function(p,g,f){(function(c){function d(q,x,y){if(!x)return g.encodeBase64Packet(q,y);var z=new FileReader;z.onload=function(){q.data=z.result;g.encodePacket(q,x,!0,y)};return z.readAsArrayBuffer(q.data)}function e(q,x,y){var z=Array(q.length);y=v(q.length,y);for(var A=function(D,E,F){x(E,function(G,H){z[D]=H;F(G,z)})},C=0;C<q.length;C++)A(C,q[C],y)}var l=f(22),n=f(23),r=f(24),v=f(25),u=
f(26),t;c&&c.ArrayBuffer&&(t=f(28));var h="undefined"!==typeof navigator&&/Android/i.test(navigator.userAgent),a="undefined"!==typeof navigator&&/PhantomJS/i.test(navigator.userAgent),b=h||a;g.protocol=3;var k=g.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},m=l(k),w={type:"error",data:"parser error"},B=f(29);g.encodePacket=function(q,x,y,z){"function"===typeof x&&(z=x,x=!1);"function"===typeof y&&(z=y,y=null);var A=void 0===q.data?void 0:q.data.buffer||q.data;if(c.ArrayBuffer&&
A instanceof ArrayBuffer){if(x){y=q.data;x=new Uint8Array(y);y=new Uint8Array(1+y.byteLength);y[0]=k[q.type];for(q=0;q<x.length;q++)y[q+1]=x[q];q=z(y.buffer)}else q=g.encodeBase64Packet(q,z);return q}if(B&&A instanceof c.Blob)return x?b?q=d(q,x,z):(x=new Uint8Array(1),x[0]=k[q.type],q=new B([x.buffer,q.data]),q=z(q)):q=g.encodeBase64Packet(q,z),q;if(A&&A.base64)return z("b"+g.packets[q.type]+q.data.data);x=k[q.type];void 0!==q.data&&(x+=y?u.encode(String(q.data),{strict:!1}):String(q.data));return z(""+
x)};g.encodeBase64Packet=function(q,x){var y="b"+g.packets[q.type];if(B&&q.data instanceof c.Blob){var z=new FileReader;z.onload=function(){var D=z.result.split(",")[1];x(y+D)};return z.readAsDataURL(q.data)}try{var A=String.fromCharCode.apply(null,new Uint8Array(q.data))}catch(D){q=new Uint8Array(q.data);A=Array(q.length);for(var C=0;C<q.length;C++)A[C]=q[C];A=String.fromCharCode.apply(null,A)}y+=c.btoa(A);return x(y)};g.decodePacket=function(q,x,y){if(void 0===q)return w;if("string"===typeof q){if("b"===
q.charAt(0))return g.decodeBase64Packet(q.substr(1),x);if(y){a:{x=q;try{x=u.decode(x,{strict:!1})}catch(z){q=!1;break a}q=x}if(!1===q)return w}y=q.charAt(0);return Number(y)==y&&m[y]?1<q.length?{type:m[y],data:q.substring(1)}:{type:m[y]}:w}y=(new Uint8Array(q))[0];q=r(q,1);B&&"blob"===x&&(q=new B([q]));return{type:m[y],data:q}};g.decodeBase64Packet=function(q,x){var y=m[q.charAt(0)];if(!t)return{type:y,data:{base64:!0,data:q.substr(1)}};q=t.decode(q.substr(1));"blob"===x&&B&&(q=new B([q]));return{type:y,
data:q}};g.encodePayload=function(q,x,y){"function"===typeof x&&(y=x,x=null);var z=n(q);if(x&&z)return B&&!b?g.encodePayloadAsBlob(q,y):g.encodePayloadAsArrayBuffer(q,y);if(!q.length)return y("0:");e(q,function(A,C){g.encodePacket(A,z?x:!1,!1,function(D){C(null,D.length+":"+D)})},function(A,C){return y(C.join(""))})};g.decodePayload=function(q,x,y){if("string"!==typeof q)return g.decodePayloadAsBinary(q,x,y);"function"===typeof x&&(y=x,x=null);if(""===q)return y(w,0,1);var z="";for(var A,C,D=0,E=
q.length;D<E;D++)if(C=q.charAt(D),":"!==C)z+=C;else{if(""===z||z!=(A=Number(z)))return y(w,0,1);C=q.substr(D+1,A);if(z!=C.length)return y(w,0,1);if(C.length){z=g.decodePacket(C,x,!1);if(w.type===z.type&&w.data===z.data)return y(w,0,1);if(!1===y(z,D+A,E))return}D+=A;z=""}if(""!==z)return y(w,0,1)};g.encodePayloadAsArrayBuffer=function(q,x){if(!q.length)return x(new ArrayBuffer(0));e(q,function(y,z){g.encodePacket(y,!0,!0,function(A){return z(null,A)})},function(y,z){y=z.reduce(function(D,E){E="string"===
typeof E?E.length:E.byteLength;return D+E.toString().length+E+2},0);var A=new Uint8Array(y),C=0;z.forEach(function(D){var E="string"===typeof D,F=D;if(E){F=new Uint8Array(D.length);for(var G=0;G<D.length;G++)F[G]=D.charCodeAt(G);F=F.buffer}E?A[C++]=0:A[C++]=1;D=F.byteLength.toString();for(G=0;G<D.length;G++)A[C++]=parseInt(D[G]);A[C++]=255;F=new Uint8Array(F);for(G=0;G<F.length;G++)A[C++]=F[G]});return x(A.buffer)})};g.encodePayloadAsBlob=function(q,x){e(q,function(y,z){g.encodePacket(y,!0,!0,function(A){var C=
new Uint8Array(1);C[0]=1;if("string"===typeof A){for(var D=new Uint8Array(A.length),E=0;E<A.length;E++)D[E]=A.charCodeAt(E);A=D.buffer;C[0]=0}D=(A instanceof ArrayBuffer?A.byteLength:A.size).toString();var F=new Uint8Array(D.length+1);for(E=0;E<D.length;E++)F[E]=parseInt(D[E]);F[D.length]=255;B&&(A=new B([C.buffer,F.buffer,A]),z(null,A))})},function(y,z){return x(new B(z))})};g.decodePayloadAsBinary=function(q,x,y){"function"===typeof x&&(y=x,x=null);for(var z=[];0<q.byteLength;){for(var A=new Uint8Array(q),
C=0===A[0],D="",E=1;255!==A[E];E++){if(310<D.length)return y(w,0,1);D+=A[E]}q=r(q,2+D.length);D=parseInt(D);A=r(q,0,D);if(C)try{A=String.fromCharCode.apply(null,new Uint8Array(A))}catch(G){for(C=new Uint8Array(A),A="",E=0;E<C.length;E++)A+=String.fromCharCode(C[E])}z.push(A);q=r(q,D)}var F=z.length;z.forEach(function(G,H){y(g.decodePacket(G,x,!0),H,F)})}}).call(g,function(){return this}())},function(p,g){p.exports=Object.keys||function(f){var c=[],d=Object.prototype.hasOwnProperty,e;for(e in f)d.call(f,
e)&&c.push(e);return c}},function(p,g,f){(function(c){function d(v){if(!v||"object"!==typeof v)return!1;if(e(v)){for(var u=0,t=v.length;u<t;u++)if(d(v[u]))return!0;return!1}if("function"===typeof c.Buffer&&c.Buffer.isBuffer&&c.Buffer.isBuffer(v)||"function"===typeof c.ArrayBuffer&&v instanceof ArrayBuffer||n&&v instanceof Blob||r&&v instanceof File)return!0;if(v.toJSON&&"function"===typeof v.toJSON&&1===arguments.length)return d(v.toJSON(),!0);for(u in v)if(Object.prototype.hasOwnProperty.call(v,
u)&&d(v[u]))return!0;return!1}var e=f(10),l=Object.prototype.toString,n="function"===typeof c.Blob||"[object BlobConstructor]"===l.call(c.Blob),r="function"===typeof c.File||"[object FileConstructor]"===l.call(c.File);p.exports=d}).call(g,function(){return this}())},function(p,g){p.exports=function(f,c,d){var e=f.byteLength;c=c||0;d=d||e;if(f.slice)return f.slice(c,d);0>c&&(c+=e);0>d&&(d+=e);d>e&&(d=e);if(c>=e||c>=d||0===e)return new ArrayBuffer(0);f=new Uint8Array(f);e=new Uint8Array(d-c);for(var l=
0;c<d;c++,l++)e[l]=f[c];return e.buffer}},function(p,g){function f(){}p.exports=function(c,d,e){function l(r,v){if(0>=l.count)throw Error("after called too many times");--l.count;r?(n=!0,d(r),d=e):0!==l.count||n||d(null,v)}var n=!1;e=e||f;l.count=c;return 0===c?d():l}},function(p,g,f){var c;(function(d,e){(function(l){function n(k){for(var m=[],w=0,B=k.length,q,x;w<B;)q=k.charCodeAt(w++),55296<=q&&56319>=q&&w<B?(x=k.charCodeAt(w++),56320==(x&64512)?m.push(((q&1023)<<10)+(x&1023)+65536):(m.push(q),
w--)):m.push(q);return m}function r(k,m){if(55296<=k&&57343>=k){if(m)throw Error("Lone surrogate U+"+k.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}function v(){if(b>=a)throw Error("Invalid byte index");var k=h[b]&255;b++;if(128==(k&192))return k&63;throw Error("Invalid continuation byte");}function u(k){if(b>a)throw Error("Invalid byte index");if(b==a)return!1;var m=h[b]&255;b++;if(0==(m&128))return m;if(192==(m&224)){var w=v();m=(m&31)<<6|w;if(128<=m)return m;throw Error("Invalid continuation byte");
}if(224==(m&240)){w=v();var B=v();m=(m&15)<<12|w<<6|B;if(2048<=m)return r(m,k)?m:65533;throw Error("Invalid continuation byte");}if(240==(m&248)&&(w=v(),B=v(),k=v(),m=(m&7)<<18|w<<12|B<<6|k,65536<=m&&1114111>=m))return m;throw Error("Invalid UTF-8 detected");}var t=String.fromCharCode,h,a,b;!(c={version:"2.1.2",encode:function(k,m){m=m||{};m=!1!==m.strict;k=n(k);for(var w=k.length,B=-1,q,x="";++B<w;){q=k[B];var y=m;if(0==(q&4294967168))q=t(q);else{var z="";0==(q&4294965248)?z=t(q>>6&31|192):0==(q&
4294901760)?(r(q,y)||(q=65533),z=t(q>>12&15|224),z+=t(q>>6&63|128)):0==(q&4292870144)&&(z=t(q>>18&7|240),z+=t(q>>12&63|128),z+=t(q>>6&63|128));q=z+=t(q&63|128)}x+=q}return x},decode:function(k,m){m=m||{};m=!1!==m.strict;h=n(k);a=h.length;b=0;k=[];for(var w;!1!==(w=u(m));)k.push(w);m=k.length;w=-1;for(var B,q="";++w<m;)B=k[w],65535<B&&(B-=65536,q+=t(B>>>10&1023|55296),B=56320|B&1023),q+=t(B);return q}},void 0!==c&&(d.exports=c))})(this)}).call(g,f(27)(p),function(){return this}())},function(p,g){p.exports=
function(f){f.webpackPolyfill||(f.deprecate=function(){},f.paths=[],f.children=[],f.webpackPolyfill=1);return f}},function(p,g){(function(){for(var f=new Uint8Array(256),c=0;64>c;c++)f["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=c;g.encode=function(d){d=new Uint8Array(d);var e,l=d.length,n="";for(e=0;e<l;e+=3)n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[e]>>2],n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[e]&
3)<<4|d[e+1]>>4],n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[e+1]&15)<<2|d[e+2]>>6],n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[e+2]&63];2===l%3?n=n.substring(0,n.length-1)+"=":1===l%3&&(n=n.substring(0,n.length-2)+"==");return n};g.decode=function(d){var e=.75*d.length,l=d.length,n=0;"="===d[d.length-1]&&(e--,"="===d[d.length-2]&&e--);var r=new ArrayBuffer(e),v=new Uint8Array(r);for(e=0;e<l;e+=4){var u=f[d.charCodeAt(e)];var t=f[d.charCodeAt(e+
1)];var h=f[d.charCodeAt(e+2)];var a=f[d.charCodeAt(e+3)];v[n++]=u<<2|t>>4;v[n++]=(t&15)<<4|h>>2;v[n++]=(h&3)<<6|a&63}return r}})()},function(p,g){(function(f){function c(u){for(var t=0;t<u.length;t++){var h=u[t];if(h.buffer instanceof ArrayBuffer){var a=h.buffer;if(h.byteLength!==a.byteLength){var b=new Uint8Array(h.byteLength);b.set(new Uint8Array(a,h.byteOffset,h.byteLength));a=b.buffer}u[t]=a}}}function d(u,t){t=t||{};var h=new l;c(u);for(var a=0;a<u.length;a++)h.append(u[a]);return t.type?h.getBlob(t.type):
h.getBlob()}function e(u,t){c(u);return new Blob(u,t||{})}var l=f.BlobBuilder||f.WebKitBlobBuilder||f.MSBlobBuilder||f.MozBlobBuilder;try{var n=2===(new Blob(["hi"])).size}catch(u){n=!1}var r;if(r=n)try{r=2===(new Blob([new Uint8Array([1,2])])).size}catch(u){r=!1}var v=l&&l.prototype.append&&l.prototype.getBlob;f=n?r?f.Blob:e:v?d:void 0;p.exports=f}).call(g,function(){return this}())},function(p,g){g.encode=function(f){var c="",d;for(d in f)f.hasOwnProperty(d)&&(c.length&&(c+="&"),c+=encodeURIComponent(d)+
"="+encodeURIComponent(f[d]));return c};g.decode=function(f){var c={};f=f.split("&");for(var d=0,e=f.length;d<e;d++){var l=f[d].split("=");c[decodeURIComponent(l[0])]=decodeURIComponent(l[1])}return c}},function(p,g){p.exports=function(f,c){var d=function(){};d.prototype=c.prototype;f.prototype=new d;f.prototype.constructor=f}},function(p,g){function f(v){var u="";do u=d[v%64]+u,v=Math.floor(v/64);while(0<v);return u}function c(){var v=f(+new Date);return v!==r?(l=0,r=v):v+"."+f(l++)}for(var d="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),
e={},l=0,n=0,r;64>n;n++)e[d[n]]=n;c.encode=f;c.decode=function(v){var u=0;for(n=0;n<v.length;n++)u=64*u+e[v.charAt(n)];return u};p.exports=c},function(p,g,f){(function(c){function d(){}function e(t){l.call(this,t);this.query=this.query||{};u||(c.___eio||(c.___eio=[]),u=c.___eio);this.index=u.length;var h=this;u.push(function(a){h.onData(a)});this.query.j=this.index;c.document&&c.addEventListener&&c.addEventListener("beforeunload",function(){h.script&&(h.script.onerror=d)},!1)}var l=f(19),n=f(31);
p.exports=e;var r=/\n/g,v=/\\n/g,u;n(e,l);e.prototype.supportsBinary=!1;e.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.iframe=this.form=null);l.prototype.doClose.call(this)};e.prototype.doPoll=function(){var t=this,h=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);h.async=!0;h.src=this.uri();h.onerror=function(b){t.onError("jsonp poll error",
b)};var a=document.getElementsByTagName("script")[0];a?a.parentNode.insertBefore(h,a):(document.head||document.body).appendChild(h);this.script=h;"undefined"!==typeof navigator&&/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var b=document.createElement("iframe");document.body.appendChild(b);document.body.removeChild(b)},100)};e.prototype.doWrite=function(t,h){function a(){b();h()}function b(){if(k.iframe)try{k.form.removeChild(k.iframe)}catch(x){k.onError("jsonp polling iframe removal error",
x)}try{q=document.createElement('<iframe src="javascript:0" name="'+k.iframeId+'">')}catch(x){q=document.createElement("iframe"),q.name=k.iframeId,q.src="javascript:0"}q.id=k.iframeId;k.form.appendChild(q);k.iframe=q}var k=this;if(!this.form){var m=document.createElement("form"),w=document.createElement("textarea"),B=this.iframeId="eio_iframe_"+this.index,q;m.className="socketio";m.style.position="absolute";m.style.top="-1000px";m.style.left="-1000px";m.target=B;m.method="POST";m.setAttribute("accept-charset",
"utf-8");w.name="d";m.appendChild(w);document.body.appendChild(m);this.form=m;this.area=w}this.form.action=this.uri();b();t=t.replace(v,"\\\n");this.area.value=t.replace(r,"\\n");try{this.form.submit()}catch(x){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===k.iframe.readyState&&a()}:this.iframe.onload=a}}).call(g,function(){return this}())},function(p,g,f){(function(c){function d(b){b&&b.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=b.perMessageDeflate;
this.usingBrowserWebSocket=t&&!b.forceNode;this.protocols=b.protocols;this.usingBrowserWebSocket||(a=h);e.call(this,b)}var e=f(20),l=f(21),n=f(30),r=f(31),v=f(32),u=f(3)("engine.io-client:websocket"),t=c.WebSocket||c.MozWebSocket;if("undefined"===typeof window)try{var h=f(35)}catch(b){}var a=t;a||"undefined"!==typeof window||(a=h);p.exports=d;r(d,e);d.prototype.name="websocket";d.prototype.supportsBinary=!0;d.prototype.doOpen=function(){if(this.check()){var b=this.uri(),k=this.protocols,m={agent:this.agent,
perMessageDeflate:this.perMessageDeflate};m.pfx=this.pfx;m.key=this.key;m.passphrase=this.passphrase;m.cert=this.cert;m.ca=this.ca;m.ciphers=this.ciphers;m.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(m.headers=this.extraHeaders);this.localAddress&&(m.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?k?new a(b,k):new a(b):new a(b,k,m)}catch(w){return this.emit("error",w)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?
(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};d.prototype.addEventListeners=function(){var b=this;this.ws.onopen=function(){b.onOpen()};this.ws.onclose=function(){b.onClose()};this.ws.onmessage=function(k){b.onData(k.data)};this.ws.onerror=function(k){b.onError("websocket error",k)}};d.prototype.write=function(b){function k(){m.emit("flush");setTimeout(function(){m.writable=!0;m.emit("drain")},0)}var m=this;this.writable=!1;for(var w=
b.length,B=0,q=w;B<q;B++)(function(x){l.encodePacket(x,m.supportsBinary,function(y){if(!m.usingBrowserWebSocket){var z={};x.options&&(z.compress=x.options.compress);m.perMessageDeflate&&("string"===typeof y?c.Buffer.byteLength(y):y.length)<m.perMessageDeflate.threshold&&(z.compress=!1)}try{m.usingBrowserWebSocket?m.ws.send(y):m.ws.send(y,z)}catch(A){u("websocket closed before onclose event")}--w||k()})})(b[B])};d.prototype.onClose=function(){e.prototype.onClose.call(this)};d.prototype.doClose=function(){"undefined"!==
typeof this.ws&&this.ws.close()};d.prototype.uri=function(){var b=this.query||{},k=this.secure?"wss":"ws",m="";this.port&&("wss"===k&&443!==Number(this.port)||"ws"===k&&80!==Number(this.port))&&(m=":"+this.port);this.timestampRequests&&(b[this.timestampParam]=v());this.supportsBinary||(b.b64=1);b=n.encode(b);b.length&&(b="?"+b);var w=-1!==this.hostname.indexOf(":");return k+"://"+(w?"["+this.hostname+"]":this.hostname)+m+this.path+b};d.prototype.check=function(){return!!a&&!("__initialize"in a&&this.name===
d.prototype.name)}}).call(g,function(){return this}())},function(p,g){},function(p,g){var f=[].indexOf;p.exports=function(c,d){if(f)return c.indexOf(d);for(var e=0;e<c.length;++e)if(c[e]===d)return e;return-1}},function(p,g,f){function c(b,k,m){this.io=b;this.nsp=k;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};m&&m.query&&(this.query=m.query);this.io.autoConnect&&this.open()}var d="function"===typeof Symbol&&"symbol"===
typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b},e=f(7);g=f(8);var l=f(38),n=f(39),r=f(40),v=f(3)("socket.io-client:socket"),u=f(30),t=f(23);p.exports=c;var h={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},a=g.prototype.emit;g(c.prototype);c.prototype.subEvents=
function(){if(!this.subs){var b=this.io;this.subs=[n(b,"open",r(this,"onopen")),n(b,"packet",r(this,"onpacket")),n(b,"close",r(this,"onclose"))]}};c.prototype.open=c.prototype.connect=function(){if(this.connected)return this;this.subEvents();this.io.open();if("open"===this.io.readyState)this.onopen();this.emit("connecting");return this};c.prototype.send=function(){var b=l(arguments);b.unshift("message");this.emit.apply(this,b);return this};c.prototype.emit=function(b){if(h.hasOwnProperty(b))return a.apply(this,
arguments),this;var k=l(arguments),m={type:(void 0!==this.flags.binary?this.flags.binary:t(k))?e.BINARY_EVENT:e.EVENT,data:k,options:{}};m.options.compress=!this.flags||!1!==this.flags.compress;"function"===typeof k[k.length-1]&&(v("emitting packet with ack id %d",this.ids),this.acks[this.ids]=k.pop(),m.id=this.ids++);this.connected?this.packet(m):this.sendBuffer.push(m);this.flags={};return this};c.prototype.packet=function(b){b.nsp=this.nsp;this.io.packet(b)};c.prototype.onopen=function(){v("transport is open - connecting");
if("/"!==this.nsp)if(this.query){var b="object"===d(this.query)?u.encode(this.query):this.query;v("sending connect packet with query %s",b);this.packet({type:e.CONNECT,query:b})}else this.packet({type:e.CONNECT})};c.prototype.onclose=function(b){v("close (%s)",b);this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",b)};c.prototype.onpacket=function(b){var k=b.type===e.ERROR&&"/"===b.nsp;if(b.nsp===this.nsp||k)switch(b.type){case e.CONNECT:this.onconnect();break;case e.EVENT:this.onevent(b);
break;case e.BINARY_EVENT:this.onevent(b);break;case e.ACK:this.onack(b);break;case e.BINARY_ACK:this.onack(b);break;case e.DISCONNECT:this.ondisconnect();break;case e.ERROR:this.emit("error",b.data)}};c.prototype.onevent=function(b){var k=b.data||[];v("emitting event %j",k);null!=b.id&&(v("attaching ack callback to event"),k.push(this.ack(b.id)));this.connected?a.apply(this,k):this.receiveBuffer.push(k)};c.prototype.ack=function(b){var k=this,m=!1;return function(){if(!m){m=!0;var w=l(arguments);
v("sending ack %j",w);k.packet({type:t(w)?e.BINARY_ACK:e.ACK,id:b,data:w})}}};c.prototype.onack=function(b){var k=this.acks[b.id];"function"===typeof k?(v("calling ack %s with %j",b.id,b.data),k.apply(this,b.data),delete this.acks[b.id]):v("bad ack %s",b.id)};c.prototype.onconnect=function(){this.connected=!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};c.prototype.emitBuffered=function(){var b;for(b=0;b<this.receiveBuffer.length;b++)a.apply(this,this.receiveBuffer[b]);this.receiveBuffer=
[];for(b=0;b<this.sendBuffer.length;b++)this.packet(this.sendBuffer[b]);this.sendBuffer=[]};c.prototype.ondisconnect=function(){v("server disconnect (%s)",this.nsp);this.destroy();this.onclose("io server disconnect")};c.prototype.destroy=function(){if(this.subs){for(var b=0;b<this.subs.length;b++)this.subs[b].destroy();this.subs=null}this.io.destroy(this)};c.prototype.close=c.prototype.disconnect=function(){this.connected&&(v("performing disconnect (%s)",this.nsp),this.packet({type:e.DISCONNECT}));
this.destroy();if(this.connected)this.onclose("io client disconnect");return this};c.prototype.compress=function(b){this.flags.compress=b;return this};c.prototype.binary=function(b){this.flags.binary=b;return this}},function(p,g){p.exports=function(f,c){for(var d=[],e=(c=c||0)||0;e<f.length;e++)d[e-c]=f[e];return d}},function(p,g){p.exports=function(f,c,d){f.on(c,d);return{destroy:function(){f.removeListener(c,d)}}}},function(p,g){var f=[].slice;p.exports=function(c,d){"string"==typeof d&&(d=c[d]);
if("function"!=typeof d)throw Error("bind() requires a function");var e=f.call(arguments,2);return function(){return d.apply(c,e.concat(f.call(arguments)))}}},function(p,g){function f(c){c=c||{};this.ms=c.min||100;this.max=c.max||1E4;this.factor=c.factor||2;this.jitter=0<c.jitter&&1>=c.jitter?c.jitter:0;this.attempts=0}p.exports=f;f.prototype.duration=function(){var c=this.ms*Math.pow(this.factor,this.attempts++);if(this.jitter){var d=Math.random(),e=Math.floor(d*this.jitter*c);c=0==(Math.floor(10*
d)&1)?c-e:c+e}return Math.min(c,this.max)|0};f.prototype.reset=function(){this.attempts=0};f.prototype.setMin=function(c){this.ms=c};f.prototype.setMax=function(c){this.max=c};f.prototype.setJitter=function(c){this.jitter=c}}])});(function(p,g,f,c,d,e,l){p.GoogleAnalyticsObject=d;p[d]=p[d]||function(){(p[d].q=p[d].q||[]).push(arguments)};p[d].l=1*new Date;e=g.createElement(f);l=g.getElementsByTagName(f)[0];e.async=1;e.src=c;l.parentNode.insertBefore(e,l)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");
